import { useQuery } from '@tanstack/react-query'
import { getAdminRevenue } from '../features/admin/api/admin-api'
import { AdminCard, AdminPageHeader, QueryState } from '../features/admin/components/admin-ui'
import { formatCurrency } from '../features/admin/lib/format'
import { RevenueChart } from '../features/admin/components/revenue-chart'

export function AdminRevenuePage() {
  const query = useQuery({ queryKey: ['admin', 'revenue'], queryFn: getAdminRevenue })
  if (!query.data) return <QueryState error={query.isError} loading={query.isPending} />
  const latest = query.data.months.at(-1)!
  return <div className="space-y-7"><AdminPageHeader description="サブスクと投げ銭による支援額を月ごとに確認できます。" title="収益管理" /><div className="grid grid-cols-4 gap-4"><AdminCard className="p-5"><p className="text-sm text-slate-500">今月の総支援額</p><p className="mt-2 text-2xl font-bold">{formatCurrency(latest.gross)}</p></AdminCard><AdminCard className="p-5"><p className="text-sm text-slate-500">サブスク</p><p className="mt-2 text-2xl font-bold">{formatCurrency(latest.subscription)}</p></AdminCard><AdminCard className="p-5"><p className="text-sm text-slate-500">投げ銭</p><p className="mt-2 text-2xl font-bold">{formatCurrency(latest.tips)}</p></AdminCard><AdminCard className="border-violet-200 bg-violet-50/40 p-5"><p className="text-sm text-violet-700">運営手数料（{query.data.feeRate}%）</p><p className="mt-2 text-2xl font-bold text-violet-950">{formatCurrency(latest.platformFee)}</p></AdminCard></div><AdminCard className="p-6"><h2 className="font-bold">月別支援額の推移</h2><p className="mt-1 text-xs text-slate-500">過去12か月の総支援額</p><div className="mt-4"><RevenueChart months={query.data.months} /></div></AdminCard><AdminCard><div className="border-b border-slate-200 px-6 py-5"><h2 className="font-bold">月別内訳</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-6 py-3.5">対象月</th><th className="px-5 py-3.5 text-right">サブスク</th><th className="px-5 py-3.5 text-right">投げ銭</th><th className="px-5 py-3.5 text-right">総支援額</th><th className="px-5 py-3.5 text-right">運営手数料</th><th className="px-6 py-3.5 text-right">Creator支払予定</th></tr></thead><tbody className="divide-y divide-slate-100">{[...query.data.months].reverse().map((month) => <tr key={month.month}><td className="px-6 py-4 font-semibold">{month.month.replace('-', '年')}月</td><td className="px-5 py-4 text-right text-slate-600">{formatCurrency(month.subscription)}</td><td className="px-5 py-4 text-right text-slate-600">{formatCurrency(month.tips)}</td><td className="px-5 py-4 text-right font-semibold">{formatCurrency(month.gross)}</td><td className="px-5 py-4 text-right text-violet-700">{formatCurrency(month.platformFee)}</td><td className="px-6 py-4 text-right font-semibold text-emerald-700">{formatCurrency(month.creatorPayout)}</td></tr>)}</tbody></table></div></AdminCard></div>
}
