import { useQuery } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { getAdminSubscribers } from '../features/admin/api/admin-api'
import { AdminCard, AdminPageHeader, EmptyState, QueryState, StatusBadge } from '../features/admin/components/admin-ui'
import { formatDate } from '../features/admin/lib/format'

export function AdminSubscribersPage() {
  const query = useQuery({ queryKey: ['admin', 'subscribers'], queryFn: getAdminSubscribers })
  const [keyword, setKeyword] = useState('')
  const [status, setStatus] = useState('all')
  const subscribers = useMemo(() => (query.data?.subscribers ?? []).filter((item) => `${item.userName} ${item.email} ${item.creatorName}`.toLowerCase().includes(keyword.toLowerCase()) && (status === 'all' || item.status === status)), [keyword, query.data, status])
  if (!query.data) return <QueryState error={query.isError} loading={query.isPending} />

  return <div className="space-y-7"><AdminPageHeader description="月額500円の応援プランに加入しているユーザーを確認できます。" title="プラン加入者" /><div className="grid grid-cols-3 gap-4"><AdminCard className="p-5"><p className="text-sm text-slate-500">現在の加入者</p><p className="mt-2 text-3xl font-bold">{query.data.subscribers.filter((item) => item.status === 'active').length}<span className="ml-1 text-sm font-medium text-slate-500">人</span></p></AdminCard><AdminCard className="p-5"><p className="text-sm text-slate-500">解約予定</p><p className="mt-2 text-3xl font-bold">{query.data.subscribers.filter((item) => item.status === 'cancel_scheduled').length}<span className="ml-1 text-sm font-medium text-slate-500">人</span></p></AdminCard><AdminCard className="p-5"><p className="text-sm text-slate-500">月間サブスク支援額</p><p className="mt-2 text-3xl font-bold">¥{(query.data.subscribers.length * 500).toLocaleString()}</p></AdminCard></div><AdminCard><div className="flex gap-3 border-b border-slate-200 p-5"><input aria-label="加入者を検索" className="h-10 w-80 rounded-lg border border-slate-300 px-3 text-sm outline-none focus:border-sky-600 focus:ring-3 focus:ring-sky-100" onChange={(event) => setKeyword(event.target.value)} placeholder="ユーザー・支援先で検索" /><select aria-label="契約状態" className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm" onChange={(event) => setStatus(event.target.value)}><option value="all">すべての状態</option><option value="active">加入中</option><option value="cancel_scheduled">解約予定</option></select><span className="ml-auto self-center text-sm text-slate-500">{subscribers.length}件</span></div>{subscribers.length === 0 ? <EmptyState>条件に一致する加入者はいません。</EmptyState> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-6 py-3.5">加入者</th><th className="px-5 py-3.5">支援先</th><th className="px-5 py-3.5">加入日</th><th className="px-5 py-3.5">次回更新日</th><th className="px-5 py-3.5">継続期間</th><th className="px-6 py-3.5">状態</th></tr></thead><tbody className="divide-y divide-slate-100">{subscribers.map((item) => <tr className="hover:bg-slate-50/70" key={item.id}><td className="px-6 py-4"><p className="font-semibold text-slate-800">{item.userName}</p><p className="mt-0.5 text-xs text-slate-500">{item.email}</p></td><td className="px-5 py-4 font-medium">{item.creatorName}</td><td className="px-5 py-4 text-slate-500">{formatDate(item.joinedAt)}</td><td className="px-5 py-4 text-slate-500">{formatDate(item.nextRenewalDate)}</td><td className="px-5 py-4">{item.supportedMonths}か月</td><td className="px-6 py-4"><StatusBadge tone={item.status === 'active' ? 'green' : 'amber'}>{item.status === 'active' ? '加入中' : '解約予定'}</StatusBadge></td></tr>)}</tbody></table></div>}</AdminCard></div>
}
